Commit changes to fix broken logo links in tutorial pages
Change src relative location to fix logo broken link

Update astropy_logo.png relative location to show logo image

Change logo and banner paths to fix broken links

Fixed missing space in L44 of navbar.html

Change spacing in navbar code block

Comment out button class in navbar code block to test

Change bootstrap syntax in navbar code block

Get rid of size specification to test navbar code block

Fix the img src path for templating

Change href to "#" to test navbar code block

Add size specifications and empty alt to test navbar

Change width and height specifications to test navbar code

Change logo size to fit navbar

Use "style" to specify height to test navbar code block

Add html_logo assignment to theme.conf file

Remove quotation marks for logo file name in theme.conf

Make further changes to theme.conf file to test theme code

Remove quotation marks around nav for source_link_position

Change navBar to navbar to test theme code

Revert changes from navbar to nav_bar for macro to test

Add html_logo = "astropy_logo.png" to conf.py

Remove logo portion that has been misplaced

Change True back to true in theme.conf

Revert to original syntax used with "style"

Add missing space in code to test

Change img src formatting to test navbar code

Comment out astropy html favicon and logo files in conf.py

Restore favicon definition statement in conf.py

Clean up conf.py file

Comment out button class in navbar code block to test

Comment out nav-brand class to test navbar code block

Rewrite navbar code snippets in navbar.html to test

Change navbar code snippets back to test navbar.html

Clean up navbar.html

Polishing up on navbar.html to test code

Clean up navbar.html further by getting rid of spaces

Change width and height properties to fit logo in navbar

Change html_favicon location to try and pick it up

Change navbar properties to try to show logo

Get rid of redundant "navbar" term in navbar.html

Revert back to previous navbar.html settings

Change height of logo to unhide image

Change relative path of img src to try and pick up logo

Change CSS attributes in navbar.html to test code

Continue changing CSS attributes to test navbar code

Uncomment html_logo path in conf.py file

Correct logo path redirect to rst-tutorials behavior

Change width of logo by implicit ratio-aspect lock

Correct logo link redirection behavior

To [http://www.astropy.org/astropy-tutorials/](http://www.astropy.org/astropy-tutorials/).

Using HTML onerror attribute to correct remaining broken error link

Fix syntax error in navbar.html file

Add missing space and forward slash in L44 of navbar.html

Change syntax to try and debug navbar.html

Update coordinates.ipynb to debug NameResolveError

NameResolveError: All Sesame queries failed. Unable to retrieve coordinates.

Update Coordinates-Intro to debug NameResolveError

Change data.conf.remote_timeout location and value in coordinates.ipynb

Further update Coordinates-Intro.ipynb to debug

Change name used in Sesame query to debug

Revise syntax of img src for logo

Remove html_logo from conf.py

Change href for navbar-brand from html to relative path

Revert Coordinates-Intro changes

Get rid of redundant spaces in L93

Revert changes made to coordinates.ipynb tutorial

Undo explicit print statement

Remove unnecessary comments regarding html_logo